### ISSUE TITLE
Repozytorium dla nowej strony

### ISSUE THREAD

**Issue by Palid** [hackerspace-silesia/hackerspace-silesia.github.io#37]
Myślę, że to jest dobre miejsce na tego typu rzeczy, więc to tu wrzucam.
W momencie gdy repo dla nowej strony zostanie utworzone, wrzucę jako organizacja odpowiednie pliki.

**Comment by lukaszo** [comment]
https://github.com/hackerspace-silesia/hs-silesia.pl
