### ISSUE TITLE
nie działające linki menu w postach

### ISSUE THREAD

**Issue by MPrusek** [hackerspace-silesia/hackerspace-silesia.github.io#38]
po wybraniu dowolnego posta z kalendarza nie działają linki w menu
przykład: http://silesia.hackerspace.pl/_i18n/pl/2014/03/20/czego-agile-nie-mowi.html#about

w _layouts/default.html linie 26-32 chyba powinny mieć site.url zamiast site.baseurl

**Comment by firemark** [comment]
Nie warto poprawiać - za niedługo ruszy nowa strona na wordpressie.
